### ISSUE TITLE
1.19 TODO

### ISSUE THREAD

**Issue by PureGero** [PureGero/MultiPaper#206]
- [x] Sync sculk sensors
- [x] Sync warden (warden spawn animation not synced; warden doesn't respond to snowballs?)
- [x] Test frog trying to eat an entity on another server
